ALTER SESSION SET CONTAINER=ORCLPDB1;

CREATE USER ORCL_USER IDENTIFIED BY PASSWORD;
ALTER USER ORCL_USER QUOTA UNLIMITED ON USERS;
GRANT DBA to ORCL_USER;

CREATE TABLE ORCL_USER.EMPLOYEES("EMPLOYEE_ID" INTEGER NOT NULL PRIMARY KEY,"FIRST_NAME" VARCHAR2(20),"LAST_NAME" VARCHAR2(25),"EMAIL" VARCHAR2(25),"PHONE_NUMBER" VARCHAR2(20),"HIRE_DATE" DATE,"JOB_ID" VARCHAR2(10),"SALARY" NUMBER(8,2),"COMMISSION_PCT" NUMBER(2,2),"MANAGER_ID" NUMBER(6,0),"DEPARTMENT_ID" NUMBER(4,0));
CREATE TABLE ORCL_USER.EMPLOYEES1("EMPLOYEE_ID" INTEGER NOT NULL PRIMARY KEY,"FIRST_NAME" VARCHAR2(20),"LAST_NAME" VARCHAR2(25),"EMAIL" VARCHAR2(25),"PHONE_NUMBER" VARCHAR2(20),"HIRE_DATE" DATE,"JOB_ID" VARCHAR2(10),"SALARY" NUMBER(8,2),"COMMISSION_PCT" NUMBER(2,2),"MANAGER_ID" NUMBER(6,0),"DEPARTMENT_ID" NUMBER(4,0));
CREATE TABLE ORCL_USER.CONSULTANTS("ID" INTEGER NOT NULL PRIMARY KEY,"FIRST_NAME" VARCHAR(50),"LAST_NAME" VARCHAR(50),"EMAIL" VARCHAR(50),"RATE" NUMBER(8,2),"STATUS" VARCHAR(20),"CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP,"UPDATED_AT" timestamp NOT NULL);
CREATE TABLE ORCL_USER.CONSULTANTS1("ID" INTEGER NOT NULL PRIMARY KEY,"FIRST_NAME" VARCHAR(50),"LAST_NAME" VARCHAR(50),"EMAIL" VARCHAR(50),"RATE" NUMBER(8,2),"STATUS" VARCHAR(20),"CREATED_AT" timestamp DEFAULT CURRENT_TIMESTAMP,"UPDATED_AT" timestamp NOT NULL);

QUIT
